---

# Features in order:
# "StartTime", "Dur", "SrcAddr", "DstAddr", "SrcPort", "DstPort", "Proto", "Flag", "ForwardingStatus", "ToS", "Pkts", "Bytes", "Label"

structure:
  delimiter: ","
  has_header: false # true or false

ip_address:
  src: 2
  dst: 3

timestamp:
  use_timediff: true, # if false don't ignore the timestamp
  idx: 0,
  format: "%Y-%m-%d %H:%M:%S"

used_features: # we use Dur, Pkts, Bytes
  1: "continuous" # continuous or categorical.
  -3: "continuous"
  -2: "continuous"

labeling:
  idx: -1
  background_label: "background" # flows with this label considered benign. Everything else malign

...