---

# Features in order:
# "StartTime", "Dur", "SrcAddr", "DstAddr", "SrcPort", "DstPort", "Proto", "Flag", "ForwardingStatus", "ToS", "Pkts", "Bytes", "Label"

structure:
  delimiter: ","
  has_header: false # true or false

ip_address:
  src: 2
  dst: 3

used_features: # we use Dur, SrcPort, DstPort, Pkts, Bytes
  1: "continuous" # continuous or categorical.
  4: "continuous"
  5: "continuous"
  -3: "continuous"
  -2: "continuous"

labeling:
  idx: -1
  background_label: "background" # flows with this label considered benign. Everything else malign

...